---
#
#/ ____|  __ \ / ____|  __ \
#| |    | |__) | (___ | |__) |__  _ __  _   _ _ __
#| |    |  ___/ \___ \|  ___/ _ \| '_ \| | | | '_ \
#| |____| |     ____) | |  | (_) | |_) | |_| | |_) |
#\_____|_|    |_____/|_|   \___/| .__/ \__,_| .__/
#                   | |                    | |
#                   |_|                    |_|

# use & for color
# use {cps} to show cps
CPSPopup: "&6CPS: &3{cps}"
...
